from typing import List, Optional
from pydantic import BaseModel, Field

class AgentResult(BaseModel):
    """The standardized outcome returned by every Agent execution node.
    
    Acts as the strict interface contract for updates and agent step transitions.
    """
    
    success: bool = Field(..., description="Indicates whether the agent executed without terminal errors")
    agent_name: str = Field(..., description="The name of the agent executing the step (e.g. IdentityAgent)")
    updated_fields: List[str] = Field(
        default_factory=list, 
        description="The dot-notation paths of state fields modified by this agent (e.g. 'identity.archetype')"
    )
    summary: str = Field(..., description="High-level text summary of changes made by the agent")
    next_agent: Optional[str] = Field(
        None, 
        description="Explicit routing suggestion for the next agent, if determined dynamically"
    )
    errors: List[str] = Field(default_factory=list, description="Collected exception or error messages")
    warnings: List[str] = Field(default_factory=list, description="Non-blocking warning alerts")
    execution_time: float = Field(..., description="Time taken to run the agent step in seconds")
    confidence: float = Field(
        1.0, 
        ge=0.0, 
        le=1.0, 
        description="Confidence score of the decisions/outputs generated by the agent (0.0 to 1.0)"
    )
    explanation: Optional[dict] = Field(
        None, 
        description="Explainability payload details justifying agent decisions"
    )
